### ISSUE TITLE
fetch failed when clicking "一键克隆+部署"

### ISSUE THREAD

**Issue by MoonInTheRiver** [Sha1rholder/use-ChatGPT-in-GFW#1]
![image](https://user-images.githubusercontent.com/32165188/235584161-f5da359c-43df-4d4e-9701-b38353e98a0a.png)

**Comment by Sha1rholder** [comment]
Netlify手动和一键在chatgpt-demo项目最近几天更新后失效了，我在想办法处理

**Comment by Sha1rholder** [comment]
问题已解决，看我新的教程
